---
slurs:
  - word: "fag"
    censored: "f*g"
  - word: "nigger"
    censored: "n*gger"
  - word: "nigga"
    censored: "n*gga"
  - word: "faggot"
    censored: "f*ggot"
  - word: "tranny"
    censored: "tr*nny"
  - word: "dyke"
    censored: "d*ke"
  - word: "chink"
    censored: "ch*nk"
  - word: "coon"
    censored: "c**n"
  - word: "gringo"
    censored: "gr*ngo"
  - word: "kike"
    censored: "k*ke"
  - word: "niglet"
    censored: "n*glet"
  - word: "beaner"
    censored: "b**ner"
  - word: "gringo"
    censored: "gr*ngo"
  - word: "retard"
    censored: "r*tard"
  - word: "libtard"
    censored: "libt*rd"

exclusions: ''
...